{% set version = "1.4.1" %}

package:
  name: iapws
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iapws/iapws-{{ version }}.tar.gz
  sha256: d65c813bb6b100a8d1ed79e00148832a0321b3063e9632a990344890acb02493

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - scipy
  run:
    - python
    - scipy

test:
  imports:
    - iapws

about:
  home: https://github.com/jjgomera/iapws
  license: GPL-3.0
  summary: Python implementation of standards from The InternationalAssociation for the Properties of Water and Steam
  license_family: GPL3

extra:
  recipe-maintainers:
    - tntmatthews
