{% set name = "iapws" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/iapws-{{ version }}.tar.gz
  sha256: 9f0faa39a967d76fc5e5f95f61d922e135453192e02bf875d07242f13d6eaa55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - scipy >=1.2

test:
  imports:
    - iapws
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jjgomera/iapws
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Python implementation of standards from The InternationalAssociation for the Properties of Water and Steam
  license_family: GPL3

extra:
  recipe-maintainers:
    - tntmatthews
    - ocefpaf
