{% set version = "1.5" %}

package:
  name: iapws
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/iapws/iapws-{{ version }}.tar.gz
  sha256: 966203e55e7f2c769d9fd8a404d5d29aff43582d148d19cb3b90d4e1271348c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
    - scipy
  run:
    - python
    - scipy

test:
  imports:
    - iapws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jjgomera/iapws
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Python implementation of standards from The InternationalAssociation for the Properties of Water and Steam
  license_family: GPL3

extra:
  recipe-maintainers:
    - tntmatthews
