{% set name = "iapws" %}
{% set version = "1.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/iapws-{{ version }}.tar.gz
  sha256: 415c5b7fd105f58c0054f7b002a85cd56643ea356bfeb157414c3f8c9ee49035

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scipy >=1.2

test:
  imports:
    - iapws
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jjgomera/iapws
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Python implementation of standards from The InternationalAssociation for the Properties of Water and Steam
  license_family: GPL3

extra:
  recipe-maintainers:
    - tntmatthews
