travis:
  secure:
    BINSTAR_TOKEN: Rz+pjeSdgUyrGBFUHO/xmgR5/lz5duqVDzKbVChH60UcFK0eXUyUlJTKFjG+484NFWrcyLNHZYcOtWMjGXqMwJlMwp1eKVH2ofzbjEEDK0A06WACVYZPDqk2rC3WwY8ifDPHOFBkidpv/WKTGtnDhqlEJBrVg896Gicf63+ajL6y78UOgpYrOriCGEQ07zlOfPKeI8TM512z7/6eBcUNtF0ObMY4eE9ko1yedFYryf+rCc9A7cadnHzVMx/ola7dgt6dapVdptP/XSfsV1tgNGex22tNqW58AYPUvwYzOXlt0bKNH9mT0/oXdhSGAkga16sV0pGnUolVHzKBTkekXYzaS+ivIJaBA5lxNRMzgdFb6DjRhqaJQZU69B4NT9UYrX7yz6C8W0bj26Ll3GwVMd0EgaOMm3a3Q1pB/JQkI69gXO2Y1LMThTx7SbPzU4lPbKJZFPBGXsLNNf9hwSgwM81sFqUYUuUJKAK70n+/nBBzPXhI/qQEmBgTFaqDU/4dKrTg2C4ZHLT6GM4HbVgaobqLrxFy2EWQU5XkpDSU+1ePbCCgp65TBHDBO0wo93ehlhYjE8Ion8/Af36wsc1DQLEcE52Ntq+kAwDN/5Y5stWkSsCe36b0S05RKLYj3G9ssHUaembGRuocfETjNbkyrKZHRCFsGdLUcio1P5q0R3c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
